version: '3.9'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mydb  # if using container Mongo
    depends_on:
      - mongo

    restart: unless-stopped

  frontend:
    build: ./client
    ports:

      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_SERVER_BASE_URL=http://localhost:5000/api
    command: ["nginx", "-g", "daemon off;"]  # fixes frontend crash
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"

    restart: unless-stopped
